#!/usr/bin/env python3
"""Emit the Dart mini-package under generated/dart/.

The output is a self-contained pub package named `hebrewcalendar_data`
that consumers reference via a `path:` dependency in pubspec.yaml.
"""
from common import ROOT, load, tanya_key, BANNER

DART_DIR = ROOT / "generated" / "dart"
LIB_DIR  = DART_DIR / "lib"
SRC_DIR  = LIB_DIR / "src"


def dart_str(s: str) -> str:
    """Emit a Dart string literal. \" and \\ get escaped; unicode passes through."""
    return "'" + s.replace("\\", "\\\\").replace("'", r"\'") + "'"


def to_dart_enum_name(screaming: str) -> str:
    """`IGGERET_HAKODESH` → `iggeretHakodesh` (Dart enum-constant style)."""
    parts = screaming.lower().split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def emit_tanya() -> str:
    entries  = load("schedules/tanya.json")
    sections = load("names/tanya_sections.json")

    lines = [BANNER]
    lines.append("part of '../hebrewcalendar_data.dart';\n")

    # ── TanyaSection enum ─────────────────────────────────────────
    lines.append("enum TanyaSection {")
    keys_sorted = list(sections.keys())  # preserve insertion order
    for k in keys_sorted:
        v = sections[k]
        lines.append(
            f"  {to_dart_enum_name(k)}({dart_str(v['en'])}, {dart_str(v['he'])}),"
        )
    lines.append("  ;")
    lines.append("  final String en;")
    lines.append("  final String he;")
    lines.append("  const TanyaSection(this.en, this.he);")
    lines.append("}\n")

    # ── TanyaPortion record type ──────────────────────────────────
    lines.append("class TanyaPortion {")
    lines.append("  final TanyaSection section;")
    lines.append("  final int chapter;   // 0 = section has no numbered chapters (front matter)")
    lines.append("  final String start;")
    lines.append("  final String end;")
    lines.append("  const TanyaPortion(this.section, this.chapter, this.start, this.end);")
    lines.append("}\n")

    lines.append("/// Key: (leap ? 1000 : 0) + month * 40 + day")
    lines.append("int tanyaKey({required bool leap, required int month, required int day}) =>")
    lines.append("    (leap ? 1000 : 0) + month * 40 + day;\n")

    # ── Schedule table ────────────────────────────────────────────
    entries.sort(key=lambda e: tanya_key(e["leap"], e["month"], e["day"]))
    lines.append("const Map<int, TanyaPortion> tanyaSchedule = {")
    for e in entries:
        if e["section"] not in sections:
            raise SystemExit(f"tanya.json references unknown section: {e['section']!r}")
        k = tanya_key(e["leap"], e["month"], e["day"])
        tag = f"L{e['month']:02d}-{e['day']:02d}" if e["leap"] else f"N{e['month']:02d}-{e['day']:02d}"
        lines.append(
            f"  {k}: TanyaPortion(TanyaSection.{to_dart_enum_name(e['section'])}, "
            f"{e['chapter']}, {dart_str(e['start'])}, {dart_str(e['end'])}),  // {tag}"
        )
    lines.append("};\n")
    return "\n".join(lines)


def emit_barrel() -> str:
    return (
        BANNER
        + "\n"
        + "library hebrewcalendar_data;\n\n"
        + "part 'src/tanya.dart';\n"
    )


def emit_pubspec() -> str:
    # Not generator-versioned yet — bump manually when publishing.
    return (
        "# GENERATED (structure) — data content is regenerated by codegen/to_dart.py\n"
        "name: hebrewcalendar_data\n"
        "description: Hebrew-calendar reference data (schedules, translations).\n"
        "version: 0.1.0\n"
        "publish_to: none\n"
        "environment:\n"
        "  sdk: '>=3.0.0 <4.0.0'\n"
    )


def main():
    SRC_DIR.mkdir(parents=True, exist_ok=True)
    (SRC_DIR / "tanya.dart").write_text(emit_tanya(), encoding="utf-8")
    (LIB_DIR / "hebrewcalendar_data.dart").write_text(emit_barrel(), encoding="utf-8")
    (DART_DIR / "pubspec.yaml").write_text(emit_pubspec(), encoding="utf-8")
    print(f"OK  dart  → {DART_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
