#!/usr/bin/env python3
"""Emit the Dart mini-package under generated/dart/.

The output is a self-contained pub package named `hebrewcalendar_data`
that consumers reference via a `path:` dependency in pubspec.yaml.
"""
from pathlib import Path
from common import ROOT, load, tanya_key, BANNER

DART_DIR = ROOT / "generated" / "dart"
LIB_DIR  = DART_DIR / "lib"
SRC_DIR  = LIB_DIR / "src"


def dart_str(s: str) -> str:
    """Emit a Dart string literal. \" and \\ get escaped; unicode passes through."""
    return "'" + s.replace("\\", "\\\\").replace("'", r"\'") + "'"


def emit_tanya() -> str:
    entries = load("schedules/tanya.json")
    sections = load("names/tanya_sections.json")

    section_he = {en: v["he"] for en, v in sections.items()}

    lines = [BANNER]
    lines.append("part of '../hebrewcalendar_data.dart';\n")
    lines.append("class TanyaPortion {")
    lines.append("  final String sectionEn;")
    lines.append("  final String sectionHe;")
    lines.append("  final int chapter;")
    lines.append("  final String start;")
    lines.append("  final String end;")
    lines.append("  const TanyaPortion(this.sectionEn, this.sectionHe, "
                 "this.chapter, this.start, this.end);")
    lines.append("}\n")

    lines.append("/// Key: (leap ? 1000 : 0) + month * 40 + day")
    lines.append("int tanyaKey({required bool leap, required int month, required int day}) =>")
    lines.append("    (leap ? 1000 : 0) + month * 40 + day;\n")

    # Sort by key so diffs are stable and readable.
    entries.sort(key=lambda e: tanya_key(e["leap"], e["month"], e["day"]))

    lines.append("const Map<int, TanyaPortion> tanyaSchedule = {")
    for e in entries:
        k = tanya_key(e["leap"], e["month"], e["day"])
        he = section_he.get(e["section"])
        if he is None:
            raise SystemExit(f"tanya_sections.json missing Hebrew for section: {e['section']!r}")
        # Comment holds the (leap, month, day) triple so search/diff is human-readable.
        tag = f"L{e['month']:02d}-{e['day']:02d}" if e["leap"] else f"N{e['month']:02d}-{e['day']:02d}"
        lines.append(
            f"  {k}: TanyaPortion({dart_str(e['section'])}, {dart_str(he)}, "
            f"{e['chapter']}, {dart_str(e['start'])}, {dart_str(e['end'])}),  // {tag}"
        )
    lines.append("};\n")
    return "\n".join(lines)


def emit_barrel() -> str:
    return (
        BANNER
        + "\n"
        + "library hebrewcalendar_data;\n\n"
        + "part 'src/tanya.dart';\n"
    )


def emit_pubspec() -> str:
    # Not generator-versioned yet — bump manually when publishing.
    return (
        "# GENERATED (structure) — data content is regenerated by codegen/to_dart.py\n"
        "name: hebrewcalendar_data\n"
        "description: Hebrew-calendar reference data (schedules, translations).\n"
        "version: 0.1.0\n"
        "publish_to: none\n"
        "environment:\n"
        "  sdk: '>=3.0.0 <4.0.0'\n"
    )


def main():
    SRC_DIR.mkdir(parents=True, exist_ok=True)
    (SRC_DIR / "tanya.dart").write_text(emit_tanya(), encoding="utf-8")
    (LIB_DIR / "hebrewcalendar_data.dart").write_text(emit_barrel(), encoding="utf-8")
    (DART_DIR / "pubspec.yaml").write_text(emit_pubspec(), encoding="utf-8")
    print(f"OK  dart  → {DART_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
